//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentExpenses
    {
        public int Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public int Id_Tenant { get; set; }
        public int Id_EstateExpense { get; set; }
        public Nullable<decimal> IndexOld { get; set; }
        public Nullable<decimal> IndexNew { get; set; }
    
        public virtual AssociationExpenses AssociationExpenses { get; set; }
        public virtual Apartments Apartments { get; set; }
    }
}
