//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartments
    {
        public Apartments()
        {
            this.ApartmentExpenses = new HashSet<ApartmentExpenses>();
            this.ApartmentPersons = new HashSet<ApartmentPersons>();
            this.AssociationCountersApartment = new HashSet<AssociationCountersApartment>();
            this.DocumentApartmentFlyers = new HashSet<DocumentApartmentFlyers>();
        }
    
        public int Id { get; set; }
        public string ExtraInfo { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public int Dependents { get; set; }
        public int id_Estate { get; set; }
        public Nullable<decimal> CotaIndiviza { get; set; }
        public int Number { get; set; }
        public Nullable<int> Id_StairCase { get; set; }
        public Nullable<bool> HasHeatHelp { get; set; }
    
        public virtual ICollection<ApartmentExpenses> ApartmentExpenses { get; set; }
        public virtual ICollection<ApartmentPersons> ApartmentPersons { get; set; }
        public virtual ICollection<AssociationCountersApartment> AssociationCountersApartment { get; set; }
        public virtual ICollection<DocumentApartmentFlyers> DocumentApartmentFlyers { get; set; }
        public virtual Associations Associations { get; set; }
        public virtual StairCases StairCases { get; set; }
    }
}
