//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentCounters
    {
        public int Id { get; set; }
        public int Id_Apartment { get; set; }
        public int Id_Counters { get; set; }
    
        public virtual Tenants Tenants { get; set; }
        public virtual Counters Counters { get; set; }
    }
}
