//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentsDebt
    {
        public int Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public bool IsPayed { get; set; }
        public int Id_Apartament { get; set; }
        public int Id_debtType { get; set; }
        public Nullable<decimal> RemainingToPay { get; set; }
    
        public virtual Apartments Apartments { get; set; }
        public virtual DebtTypes DebtTypes { get; set; }
    }
}
