//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationExpensesUnitPrices
    {
        public int Id { get; set; }
        public Nullable<decimal> PricePerExpenseUnit { get; set; }
        public int Id_assCounter { get; set; }
        public int Id_assExpense { get; set; }
    
        public virtual AssociationCounters AssociationCounters { get; set; }
        public virtual AssociationExpenses AssociationExpenses { get; set; }
    }
}
