//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationCounters
    {
        public AssociationCounters()
        {
            this.AssociationCountersApartment = new HashSet<AssociationCountersApartment>();
            this.InvoiceIndexes = new HashSet<InvoiceIndexes>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public int Id_Estate { get; set; }
        public Nullable<int> Id_StairCase { get; set; }
        public Nullable<int> Id_Expense { get; set; }
    
        public virtual ICollection<AssociationCountersApartment> AssociationCountersApartment { get; set; }
        public virtual Associations Associations { get; set; }
        public virtual Expenses Expenses { get; set; }
        public virtual StairCases StairCases { get; set; }
        public virtual ICollection<InvoiceIndexes> InvoiceIndexes { get; set; }
    }
}
