//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociationCountersStairCase
    {
        public int Id { get; set; }
        public int Id_AssCounter { get; set; }
        public Nullable<int> Id_StairCase { get; set; }
    
        public virtual AssociationCounters AssociationCounters { get; set; }
        public virtual StairCases StairCases { get; set; }
    }
}
