//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBooks
    {
        public int Id { get; set; }
        public int Id_EstateExpense { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string ExtraInfo { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> LastModifiedOn { get; set; }
        public Nullable<int> RedistributeType { get; set; }
    
        public virtual EstateExpenses EstateExpenses { get; set; }
        public virtual EstateExpensesRedistributionTypes EstateExpensesRedistributionTypes { get; set; }
    }
}
