//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAssociationMonthlyExpenses
    {
        public int Id { get; set; }
        public int AssociationId { get; set; }
        public int year { get; set; }
        public int month { get; set; }
        public string rawFile { get; set; }
        public string fileType { get; set; }
    
        public virtual Associations Associations { get; set; }
    }
}
