//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public Expenses()
        {
            this.AssociationCounters = new HashSet<AssociationCounters>();
            this.AssociationExpenses = new HashSet<AssociationExpenses>();
            this.InvoiceSubcategoryTypes = new HashSet<InvoiceSubcategoryTypes>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> specialType { get; set; }
        public Nullable<int> LegalType { get; set; }
    
        public virtual ICollection<AssociationCounters> AssociationCounters { get; set; }
        public virtual ICollection<AssociationExpenses> AssociationExpenses { get; set; }
        public virtual ExpenseTypes ExpenseTypes { get; set; }
        public virtual ICollection<InvoiceSubcategoryTypes> InvoiceSubcategoryTypes { get; set; }
    }
}
