//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public Expenses()
        {
            this.Counters = new HashSet<Counters>();
            this.EstateExpenses = new HashSet<EstateExpenses>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Counters> Counters { get; set; }
        public virtual ICollection<EstateExpenses> EstateExpenses { get; set; }
    }
}
