//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceSubcategories
    {
        public int Id { get; set; }
        public int Id_Invoice { get; set; }
        public int Id_subCategType { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<decimal> service { get; set; }
        public Nullable<decimal> penalties { get; set; }
        public Nullable<decimal> PricePerUnit { get; set; }
    
        public virtual Invoices Invoices { get; set; }
        public virtual InvoiceSubcategoryTypes InvoiceSubcategoryTypes { get; set; }
    }
}
