//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceIndexes
    {
        public int Id { get; set; }
        public Nullable<decimal> IndexOld { get; set; }
        public Nullable<decimal> IndexNew { get; set; }
        public int Id_Invoice { get; set; }
        public Nullable<int> Id_Counter { get; set; }
    
        public virtual Counters Counters { get; set; }
        public virtual Invoices Invoices { get; set; }
    }
}
