//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public Invoices()
        {
            this.InvoiceIndexes = new HashSet<InvoiceIndexes>();
            this.InvoiceSubcategories = new HashSet<InvoiceSubcategories>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> Id_EstateExpense { get; set; }
        public Nullable<int> Id_StairCase { get; set; }
        public string Description { get; set; }
        public Nullable<int> id_Redistributiontype { get; set; }
        public Nullable<System.DateTime> issueDate { get; set; }
        public string issueNumber { get; set; }
        public Nullable<int> id_assCounter { get; set; }
    
        public virtual AssociationCounters AssociationCounters { get; set; }
        public virtual AssociationExpenses AssociationExpenses { get; set; }
        public virtual AssociationExpensesRedistributionTypes AssociationExpensesRedistributionTypes { get; set; }
        public virtual ICollection<InvoiceIndexes> InvoiceIndexes { get; set; }
        public virtual StairCases StairCases { get; set; }
        public virtual ICollection<InvoiceSubcategories> InvoiceSubcategories { get; set; }
    }
}
