//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        public int Id { get; set; }
        public Nullable<decimal> Value { get; set; }
        public int Id_StairCase { get; set; }
        public int Id_CashBook { get; set; }
    
        public virtual CashBooks CashBooks { get; set; }
        public virtual StairCases StairCases { get; set; }
    }
}
