//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceSubcategoryTypes
    {
        public InvoiceSubcategoryTypes()
        {
            this.InvoiceSubcategories = new HashSet<InvoiceSubcategories>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
        public int Id_Expense { get; set; }
    
        public virtual Expenses Expenses { get; set; }
        public virtual ICollection<InvoiceSubcategories> InvoiceSubcategories { get; set; }
    }
}
