//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.Associations = new HashSet<Associations>();
            this.PartnerRights = new HashSet<PartnerRights>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Password { get; set; }
        public int Id_Locality { get; set; }
        public int Id_PartnerType { get; set; }
        public string Name { get; set; }
        public Nullable<bool> SeenTutorial { get; set; }
    
        public virtual ICollection<Associations> Associations { get; set; }
        public virtual Localities Localities { get; set; }
        public virtual ICollection<PartnerRights> PartnerRights { get; set; }
        public virtual PartnerTypes PartnerTypes { get; set; }
    }
}
