//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        public Persons()
        {
            this.ApartmentPersons = new HashSet<ApartmentPersons>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Password { get; set; }
        public int Id_Locality { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ApartmentPersons> ApartmentPersons { get; set; }
    }
}
