//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistriesHomeDaily
    {
        public RegistriesHomeDaily()
        {
            this.RegistriesHome = new HashSet<RegistriesHome>();
        }
    
        public int Id { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal OpeningAmount { get; set; }
        public decimal ClosingAmount { get; set; }
        public int Id_association { get; set; }
    
        public virtual Associations Associations { get; set; }
        public virtual ICollection<RegistriesHome> RegistriesHome { get; set; }
    }
}
