//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StairCases
    {
        public StairCases()
        {
            this.Counters = new HashSet<Counters>();
            this.Invoices = new HashSet<Invoices>();
            this.Tenants = new HashSet<Tenants>();
        }
    
        public int Id { get; set; }
        public string Nume { get; set; }
        public int Id_Estate { get; set; }
        public Nullable<decimal> Indiviza { get; set; }
    
        public virtual ICollection<Counters> Counters { get; set; }
        public virtual Estates Estates { get; set; }
        public virtual ICollection<Invoices> Invoices { get; set; }
        public virtual ICollection<Tenants> Tenants { get; set; }
    }
}
