//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StairCases
    {
        public StairCases()
        {
            this.Apartments = new HashSet<Apartments>();
            this.AssociationCountersStairCase = new HashSet<AssociationCountersStairCase>();
            this.Invoices = new HashSet<Invoices>();
        }
    
        public int Id { get; set; }
        public string Nume { get; set; }
        public int Id_Estate { get; set; }
        public Nullable<decimal> Indiviza { get; set; }
    
        public virtual ICollection<Apartments> Apartments { get; set; }
        public virtual ICollection<AssociationCountersStairCase> AssociationCountersStairCase { get; set; }
        public virtual Associations Associations { get; set; }
        public virtual ICollection<Invoices> Invoices { get; set; }
    }
}
