//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Administratoro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenants
    {
        public Tenants()
        {
            this.ApartmentCounters = new HashSet<ApartmentCounters>();
            this.TenantExpenses = new HashSet<TenantExpenses>();
            this.TenantPersons = new HashSet<TenantPersons>();
        }
    
        public int Id { get; set; }
        public string ExtraInfo { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public int Dependents { get; set; }
        public int id_Estate { get; set; }
        public Nullable<decimal> CotaIndiviza { get; set; }
        public int Number { get; set; }
        public Nullable<int> Id_StairCase { get; set; }
    
        public virtual ICollection<ApartmentCounters> ApartmentCounters { get; set; }
        public virtual Estates Estates { get; set; }
        public virtual StairCases StairCases { get; set; }
        public virtual ICollection<TenantExpenses> TenantExpenses { get; set; }
        public virtual ICollection<TenantPersons> TenantPersons { get; set; }
    }
}
